# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.9-for-vscode"
    hooks:
      - id: prettier
# - repo: https://github.com/dnephin/pre-commit-golang
#   rev: v0.5.1
#   hooks:
#   - id: go-fmt
#   - id: go-imports
#   - id: no-go-testing
#   - id: golangci-lint
#   - id: go-unit-tests
#     # - id: validate-toml
# - repo: https://github.com/golangci/golangci-lint   # golangci-lint hook repo
#   rev: v1.53.3   # golangci-lint hook repo revision
#   hooks:
#   - id: golangci-lint     # hook id
